version: 1.0.{build}

branches:
  only:
    - master
    
image: Visual Studio 2019
configuration: Release
build:
  parallel: true
  project: Pixeval.sln
  
artifacts:
  - path: bin\$(configuration)\netcoreapp3.0\*
    name: myapp
