version: 1.0.{build}

branches:
  only:
    - master
    
image: Visual Studio 2019
configuration: Release


before_build:
  - nuget restore

build:
  parallel: true
  project: Pixeval.sln
  
artifacts:
  - path: bin\$(configuration)\netcoreapp3.0\*
    name: myapp

cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
